### ISSUE TITLE
make the package functional with custom environments without changing package code.

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#39]
Love your work so far.

But I have a... let's call it a feature request.
Right now, I have to go into your code, add my custom environment to your scenarios folder, and make it visible in the __init__,py file.
Just so you can load the environment for me. 
make_env.py
```
    if not scenario_name.endswith(".py"):
        scenario_name += ".py"
    scenario = scenarios.load(scenario_name).Scenario()
```

I would suggest you to make a function called make_custom_env(), which takes a Scenario as an input parameter.
This would enable me to have my own custom environments located inside my own repositories instead of having a link to some old fork of your library. 

```
def make_env(
    scenario_name,
    num_envs: int = 32,
    device: DEVICE_TYPING = "cpu",
    continuous_actions: bool = True,
    wrapper: Optional[
        Wrapper
    ] = None,  # One of: None, vmas.Wrapper.RLLIB, and vmas.Wrapper.GYM
    max_steps: Optional[int] = None,
    seed: Optional[int] = None,
    **kwargs,
):
    # load scenario from script
    if not scenario_name.endswith(".py"):
        scenario_name += ".py"
    scenario = scenarios.load(scenario_name).Scenario()
    env = Environment(
        scenario,
        num_envs=num_envs,
        device=device,
        continuous_actions=continuous_actions,
        max_steps=max_steps,
        seed=seed,
        **kwargs,
    )

    return wrapper.get_env(env) if wrapper is not None else env


def make_custom_env(
    scenario: BaseScenario,
    num_envs: int = 32,
    device: DEVICE_TYPING = "cpu",
    continuous_actions: bool = True,
    wrapper: Optional[
        Wrapper
    ] = None,  # One of: None, vmas.Wrapper.RLLIB, and vmas.Wrapper.GYM
    max_steps: Optional[int] = None,
    seed: Optional[int] = None,
    **kwargs,
):
    env = Environment(
        scenario,
        num_envs=num_envs,
        device=device,
        continuous_actions=continuous_actions,
        max_steps=max_steps,
        seed=seed,
        **kwargs,
    )

    return wrapper.get_env(env) if wrapper is not None else env
```

I have made this change in my clone repo, but you might find it useful enough to add it as well.

**Comment by matteobettini** [comment]
Cool! this id ultra useful thanks! 

Check out commit cb8ff45, does it do what you need?



> Right now, I have to go into your code, add my custom environment to your scenarios folder, and make it visible in the **init**,py file.

PS what do you mean by make it visible? once in the folder you shouldn't have to touch the init file right?

**Comment by Zartris** [comment]
HI @matteobettini, It was exactly that!
Thanks for the quick change.

**Comment by Zartris** [comment]
Hey sorry to bring this up again, but it seems the same functionality would be great for
 interactive_rendering.py
 ```
Traceback (most recent call last):
  File "/home/zartris/code/python/MyProject/MyScenario.py", line 286, in <module>
    render_interactively(scenario, control_two_agents=False)
  File "/home/zartris/code/python/VectorizedMultiAgentSimulator/vmas/interactive_rendering.py", line 273, in render_interactively
    if scenario_name.endswith(".py"):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'lp_collision_avoidance' object has no attribute 'endswith'
```

**Comment by matteobettini** [comment]
Thanks, will add!

**Comment by matteobettini** [comment]
Check now if it is ok
