### ISSUE TITLE
Error when running rllib example

### ISSUE THREAD

**Issue by kfu02** [proroklab/VectorizedMultiAgentSimulator#60]
Hi, I would like to run the rllib example on VMAS. Currently the use_vmas_env.py example works great. However I get this error when running the rllib example: 
```
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/air/integrations/wandb.py", line 367, in __reduce__
    raise RuntimeError("_WandbLoggingProcess is not pickleable.")
RuntimeError: _WandbLoggingProcess is not pickleable.
```
Any help regarding what is wrong would be appreciated. I am on Python 3.8, ray/rllib 2.2.0, and wandb 0.15.11. Thank you!

**Comment by kfu02** [comment]
Here is the full error log, if that helps:


```
❯ python rllib.py
2023-09-25 20:59:08,662 INFO worker.py:1538 -- Started a local Ray instance.
Ray init!
2023-09-25 20:59:09,673 INFO wandb.py:250 -- Already logged into W&B.
Traceback (most recent call last):
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 928, in _wait_and_handle_event
    self._on_pg_ready(next_trial)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 1018, in _on_pg_ready
    if not _start_trial(next_trial) and next_trial.status != Trial.ERROR:
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 1010, in _start_trial
    self._callbacks.on_trial_start(
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/tune/callback.py", line 317, in on_trial_start
    callback.on_trial_start(**info)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/tune/logger/logger.py", line 135, in on_trial_start
    self.log_trial_start(trial)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/air/integrations/wandb.py", line 527, in log_trial_start
    self._trial_processes[trial].start()
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/Users/kevinfu/opt/miniconda3/envs/vmas/lib/python3.8/site-packages/ray/air/integrations/wandb.py", line 367, in __reduce__
    raise RuntimeError("_WandbLoggingProcess is not pickleable.")
RuntimeError: _WandbLoggingProcess is not pickleable.
```

**Comment by kfu02** [comment]
Ah after some more digging I found that this seems to be an issue on non-Linux systems running Ray==2.2: https://github.com/ray-project/ray/issues/31366. I am using an M1 Mac so that would explain it.

I will try this example on a Linux machine and report back.

**Comment by matteobettini** [comment]
Hello,

Yes this seems like a ray issue.

You can remove the wandb logger or try another version.

Unfortunately i cannot guarantee compatibility with later ray versions as they update very frequently with breaking changes.

Currently I am focusing on TorchRL where the vmas wrapper is integrated in the lib and is automatically checked and updated for each version. See the TorchRL section in the readme if interested.

**Comment by kfu02** [comment]
Ah I see. I will consider using TorchRL then. Thank you!
