### ISSUE TITLE
BUG: DifferentialDrive debug scenario does not launch

### ISSUE THREAD

**Issue by kfu02** [proroklab/VectorizedMultiAgentSimulator#79]
When running the DifferentialDrive debug scenario, I'm getting an error and nothing launches. The debug/waterfall.py scenario works great, however. Am I missing something?
```
❯ python vmas/scenarios/debug/diff_drive.py
Traceback (most recent call last):
  File "/home/kfu38/star-lab/het-mamp/VectorizedMultiAgentSimulator/vmas/scenarios/debug/diff_drive.py", line 110, in <module>
    render_interactively(__file__, control_two_agents=True)
  File "/home/kfu38/star-lab/het-mamp/VectorizedMultiAgentSimulator/vmas/interactive_rendering.py", line 316, in render_interactively
    InteractiveEnv(
  File "/home/kfu38/star-lab/het-mamp/VectorizedMultiAgentSimulator/vmas/interactive_rendering.py", line 76, in __init__
    self.env.render()
  File "/home/kfu38/star-lab/het-mamp/VectorizedMultiAgentSimulator/vmas/simulator/environment/gym.py", line 79, in render
    return self._env.render(
           ^^^^^^^^^^^^^^^^^
  File "/home/kfu38/star-lab/het-mamp/VectorizedMultiAgentSimulator/vmas/simulator/environment/environment.py", line 570, in render
    all_poses = torch.stack(
                ^^^^^^^^^^^^
RuntimeError: stack expects a non-empty TensorList
```

**Comment by kfu02** [comment]
Apologies, my fork was out of date. The latest version works well.
